######################################################################
# Automatically generated by qmake (2.01a) wt. maj 9 17:29:23 2017
######################################################################

OBJECTS_DIR=./obj
INCLUDEPATH=inc
MOC_DIR=./moc
RCC_DIR=./rcc
QT+=widgets
QMAKE_CXXFLAGS+=-std=c++11
TEMPLATE = app
TARGET = d_a
DEPENDPATH += src src src src
INCLUDEPATH += .

# Input
SOURCES += src/main.cpp src/odbieranie.cpp src/okno.cpp src/transparam.cpp
