######################################################################
# Automatically generated by qmake (2.01a) pon. maj 8 12:49:54 2017
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += inc/ .
QT+= network

# Input
HEADERS +=  inc/transparam.hh  inc/okno.hh inc/odbieranie.hh \
    inc/socket.hh
SOURCES +=  src/transparam.cpp  src/okno.cpp  src/odbieranie.cpp  src/main.cpp \
    src/socket.cpp
